name: Build btop

on:
  workflow_dispatch:
    inputs:
      btop-version:
        required: false
        type: string
      release-version:
        required: false
        type: string
      description:
        required: false
        type: string
  push:
    branches: ["main"]

env:
  BTOP_RELEASE: main #v1.3.2

jobs:
  build_macos:
    name: Build MacOS universal
    runs-on: macos-12
    steps:
      - name: Install dependencies
        run: |
          brew install cmake git llvm ninja lowdown

      - name: Build
        run: |
          git clone https://github.com/bjia56/btop.git
          cd btop
          git checkout ${{ inputs.btop-version || env.BTOP_RELEASE }}

          export LLVM_PREFIX="$(brew --prefix llvm)"
          export CXX="$LLVM_PREFIX/bin/clang++"
          export CPPFLAGS="-I$LLVM_PREFIX/include"
          export LDFLAGS="-L$LLVM_PREFIX/lib -L$LLVM_PREFIX/lib/c++ -Wl,-rpath,$LLVM_PREFIX/lib/c++ -fuse-ld=$LLVM_PREFIX/bin/ld64.lld"
          cmake \
            -B build \
            -G Ninja \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/btop-install \
            "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15

          cmake --build build --parallel
          cmake --install build

          cd ${{ github.workspace }}
          rm -rf btop
          mv btop-install btop

          tar -czf ${{ github.workspace }}/btop.tar.gz btop
          zip ${{ github.workspace }}/btop-darwin-universal.zip $(tar tf ${{ github.workspace }}/btop.tar.gz)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: btop-darwin-universal-zip
          path: ./btop-darwin-universal.zip

  build_linux:
    name: Build Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Set up zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Build
        run: |
          git clone https://github.com/bjia56/btop.git
          cd btop
          git checkout ${{ inputs.btop-version || env.BTOP_RELEASE }}

          export CXX="zig c++ -target ${{ matrix.arch }}-linux-gnu.2.17"
          export CC="zig cc -target ${{ matrix.arch }}-linux-gnu.2.17"
          cmake \
            -B build \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/btop-install \
            -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }}

          cmake --build build --parallel
          cmake --install build

          cd ${{ github.workspace }}
          rm -rf btop
          mv btop-install btop

          tar -czf ${{ github.workspace }}/btop.tar.gz btop
          zip ${{ github.workspace }}/btop-linux-${{ matrix.arch }}.zip $(tar tf ${{ github.workspace }}/btop.tar.gz)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: btop-linux-${{ matrix.arch }}-zip
          path: ./btop-linux-${{ matrix.arch }}.zip

  release:
    if: ${{ inputs.release-version }}
    needs: build_macos
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: btop-*
          path: /tmp/btop/
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/btop/*.zip
          tag_name: ${{ inputs.release-version }}
          body: ${{ inputs.description }}
